// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:pokemon_storage_service/src/entity/pokemon_entity.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(PokemonEntityAdapter());
    registerAdapter(PokemonSpritesEntityAdapter());
    registerAdapter(PokemonTypeEntityAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(PokemonEntityAdapter());
    registerAdapter(PokemonSpritesEntityAdapter());
    registerAdapter(PokemonTypeEntityAdapter());
  }
}
